# soubor s parametrama programu

input_format: "structured_csv" # např. "structured_csv" (doporučeno), "txt", "csv", "json", ale nepřeháně
input_file: "vstupni_data.csv" # název vstupního souboru
tasks:
  - "none" # nedělat nic
  # dále to co je v zadání, jména začínat číslem úkolu, pak stručně název, např. "2_graphic_analysis
  #- "2_graphic_analysis" # grafická analýza dat
  #- "4_normal_distribution_parameters"
  #- "7_median_equality_test"
  #- "10_regression_significance_test"